spring.application.name=Fraud-Detection-System


spring.datasource.url=jdbc:mysql://localhost:3306/fraud-detection-data
spring.datasource.username=root
spring.datasource.password=Anurag@2403

spring.jpa.hibernate.ddl-auto=update
